FROM nvidia/cuda:10.2-cudnn7-devel-ubuntu18.04
MAINTAINER i@imux.top

RUN apt-get update && apt-get install -y \
      build-essential \
      git \
      libatlas-base-dev \
      libatlas-dev \
      libboost-all-dev \
      libgflags-dev \
      libgoogle-glog-dev \
      libhdf5-dev \
      libleveldb-dev \
      liblmdb-dev \
      libopencv-dev \
      libprotobuf-dev \
      libsnappy-dev \
      lsb-release \
      protobuf-compiler \
      python-dev \
      python-numpy \
      python-pip \
      python-setuptools \
      python-scipy \
      wget \
    && rm -rf /var/lib/apt/lists/*
RUN pip install --upgrade pip

RUN git clone https://github.com/llfl/openpose
RUN cd openpose && mkdir -p build && cd build \
    && cmake -DCMAKE_BUILD_TYPE=Release .. && make -j"$(nproc)"

# RUN cd openpose/models && ./getModels.sh

WORKDIR /openpose

CMD ./build/examples/user_code/magicstick2.bin